.github/workflows/CI.yml, .vscode/extensions.json, README.md, package.json, tsconfig.json, yarn.lock
Improve React App:
- Vulnerabilty scan in CI (even if I set dependabot up)
- rollback `eslint-plugin-import-helpers` to previous version, compatible with `eslint 8.x`
- Add recommendations (requirement...) for`prettier` and `ESLint` extensions
=> Improvements

app/submitQuery/page.tsx, tailwind.config.ts
Fixing issue #21 
Fix: if dark mode is activated the colors change to have a correct display
How to test:
Launch the app with yarn dev
Reach localhost:3000
Check that the page is easily readable in light mode and in dark mode
=> Fixing issue #21: display in dark mode

.github/pull_request_template.md, .github/workflows/CI.yml
Fix issue #20 creating a PR template to make it easier and quicker to create a **_good_** PR.
=> Fix issue #20: create a template for PRs

app/layout.tsx, app/visualize/layout.tsx, app/visualize/page.tsx, components/Header.tsx, components/index.ts
Fix issue #36 
- Create a second page to visualize the query plan, so that we can test different packages here
- Create a header to navigate between pages
- Run the app
- Try to go to the visualization page (/visualize)
=> Fix issue #36: Create a header and a second page

app/timeline/layout.tsx, app/timeline/page.tsx, components/CoreTimeline.tsx, components/Header.tsx, components/index.ts, components/timeline/CoreTimeline.tsx, components/timeline/RetrievalDialog.tsx, components/timeline/index.ts, lib/functions/buildTimeline.ts, lib/functions/index.ts, lib/types/index.ts, lib/types/queryPlan.ts, lib/types/timeline.ts
Fix issue #42 
Create a timeline page to visualize the query plan
Run the app, send a query and go to the timeline page
Next steps:
=> Fix issue #42: create a timeline

.github/pull_request_template.md, README.md
Updating some of the documentation
=> feat: updating doc

app/nodes/page.tsx, app/summary/page.tsx, app/timeline/page.tsx, components/Header.tsx, components/PlanSelector.tsx, lib/redux/queryPlanReducer.ts
Closes #55 
Unify the component to choose the Querypass
_Provide steps to test the changes made in this pull request._
_Don't forget to mention any dependencies that need to be installed._
- Send a query plan
- Go to any other page and try changing the query pass
=> Fix issue #55: PlanSelector in header

.github/workflows/CI.yml, app/nodes/page.tsx, app/summary/page.tsx, jest.config.ts, lib/functions/buildTimeline.test.ts, lib/functions/index.ts, lib/functions/postRequest.test.ts, lib/functions/slowestNodes.test.ts, lib/functions/slowestNodes.ts, lib/functions/summary.test.ts, lib/functions/summary.ts, package.json, yarn.lock
Closes #66 
Implement unit test for functions
- Install the new dependencies: `yarn install:ci`
- Launch the tests: `yarn test`
=> Fix issue #66: Create unit tests

app/timeline/page.tsx, components/CoreTimeline.tsx, lib/functions/buildTimeline.test.ts, lib/functions/buildTimeline.ts
Closes #76 
- Add total number of cores, even if unused
- Write in front of each row the core number
- Submit a query
- Go to the timeline
- See the result, and test the zoom a bit
=> Fix issue #76: Get total number of cores

app/submit-query/page.tsx, lib/types/queryPlan.ts, package.json, yarn.lock
Closes #91
Check the query plan type when submitting a new query plan. If some values are missing, they are replaced by default values ("", or 0 or [])
Add new dependencies `yarn install:ci`
Try adding several query plans and go on all the pages to see if it works
=> feat: add check query plan type at runtime

components/FileExporter.tsx, components/RetrievalDialog.tsx
Closes #111 
Clicking on a timeline element displays a more readable card than the raw JSON
Go to page: timeline
Click on the parts of the timeline, check that it displays the information correctly
=> feat: custom visualisation of nodes

README.md, app/nodes/page.tsx, app/timeline/page.tsx, components/timeline/TimelineLegend.tsx, components/timeline/index.ts
Closes #125 
- Fix a few imports
- Test the ability of Vercel to comment this PR to give the link to the dev deployment
- Add deployment information in README
Click on the link in the comment that should appear from Vercel.
=> Fix issue #125: Deployment (and some others)

lib/functions/aggregateData.test.ts
Closes #139 
- Add tests for the `aggregateData` function
`yarn test` (the pipeline will do it for you)
=> Fix issue #139: Tests for aggregateData

lib/functions/adjustTimings.test.ts, lib/types/queryPlan.ts
Closes #138
Add three tests for the adjustTimings function
The CI will test the function.
Look at the code and tell me if some others relevant tests are needed
=> Fix issue #138: Tests for adjustTimings

app/timeline/page.tsx, lib/functions/aggregation/adjustTimings.test.ts, lib/functions/aggregation/adjustTimings.ts, lib/functions/aggregation/aggregateData.test.ts, lib/functions/aggregation/aggregateData.ts, lib/functions/aggregation/index.ts, lib/functions/index.ts
Closes #147 
In all pages, use `aggregateData` and only `aggregateData`
- Send a query
- Go to all pages and check that it still works as expected, and that you can get back to the node of the correct pass
=> Fix issue #147: aggregateData function

README.md
Closes #161 
adding nodes and passes routes on readme
No test. Check readme
If there is minor changes/typo to correct, you can assign me or commit them directly here
=> adding nodes and passes routes on readme

app/nodes/page.tsx, app/passes/page.tsx, app/submit-query/page.tsx, app/summary/page.tsx, app/timeline/page.tsx, components/PlanSelector.tsx, components/RetrievalDialog.tsx, components/nodes/NodesTable.tsx, components/timeline/CoreProcesses.tsx, components/timeline/TimelineDiv.tsx, lib/functions/index.ts
Closes #178 
Use hooks to optimize memory and computation
- Check that it still works (and better if possible)
=> Fix issue #178: Use hooks

app/submit-query/page.tsx, app/submit-query/ui/HelpCard.tsx, app/submit-query/ui/ManualMode.tsx, app/submit-query/ui/QueryPlanMode.tsx, app/submit-query/ui/ResultQueryPlan.tsx, components/FileExporter.tsx, components/FileUploader.tsx, lib/redux/queryPlanReducer.ts, lib/types/queryPlan.ts
Closes #179 
- Add a loading information when processing the file
- Don't display too large Query Plans, or else it crashes
- Load the query plan of #160 and now it should work (slowly, but it works)
=> Fix issue#179: Handle large files

components/Providers.tsx
Closes #190 
- Fix white flickering on first load because of MUI
- You shouldn't see weird things about white things anymore
- Using `extendTheme` instead of `createTheme` is enough
- Fun fact: even on MUI's own website, they have the white flickering... We don't :P
=> Fix issue #190: MUI white flickering on first load

app/nodes/page.tsx, app/timeline/page.tsx
Closes #189 
Add debounce on sliders and text inputs
- Send a query or load a query plan
- Go to timeline page and test scale and threshold sliders
- Go to nodes page and test slider
=> Fix issue #189: debounce state updates

app/submit-query/page.tsx, app/submit-query/ui/QueryMode.tsx
Closes #202  
Provide clearer names for submit modes components
- Check that it still work
-
=> fix issue #202: refactor submit modes
