tibo-mllr/activeviam-projet

app/submitQuery/page.tsx
Fixing issue #22 
Fix: the user can now directly submit his MDX query, for example: SELECT ...
Before, he had to enter {"mdx":"SELECT ..."}. This syntax does not work anymore.
**How to test:**
- Launch the app with ```yarn dev```
- Reach localhost:3000
- Check that submitting a direct MDX request works correctly
=> fixing issue #22 : MDX request can now be directly submitted

app/submit-query/page.tsx, lib/index.ts, lib/queryPlan.ts
Fix issue #24 
Create and use the type of the QueryPlan response, according to [this site](https://activepivot-ranch.activeviam.com:6100/activeviam/swagger-ui/index.html#/queries-rest-service-controller/mdxQueryPlan#model-JsonQueryPlanData)'s `JsonQueryPlanData` schema.
Send an MDX query and test that the response still displays correctly.
Woohoo, the template works!
=> Fix issue #24: Query Plan type

lib/functions/postRequest.ts, lib/redux/queryPlanReducer.ts
Not related to an open issue
data must be an array of QueryPlan and not a single QueryPlan
Check that the type of the shared data is correct: an array of QueryPlan and that the properties can be called
=> fix: data is an array of QueryPlan

app/summary/page.tsx, package.json, yarn.lock
Not related to an issue
Adding pie charts on the summary page for Elapsed timings (not the execution context ones) and the retrievals per type
- Color is the same for a given retrievalType on all the page
- retrievals are now ranked in descending order for their elapsed timings and their number of appearances
Launch the app
go to localhost:3000/summary
Check that there is two pie charts working properly, with the correct color correspondance and data ordered in descending order
=> Summary page improvement

app/nodes/layout.tsx, app/nodes/page.tsx, components/Header.tsx, lib/functions/slowestNodes.ts, lib/types/queryPlan.ts
Fix issue #41  
Add a page to visualize the slowest nodes
you can choose a query plan pass and the number of nodes you wan to see
Launch the app.
Go to the "Nodes" page.
Try to change the pass and the number of nodes
(No added dependency)
=> Fix issue #41: 10 slowest nodes

app/timeline/page.tsx, components/timeline/CoreTimeline.tsx
Closes #58 
Use a Box instead of a Button as the latter has a minimum size (hence the overlap when trying to reduce the scale)
- Send a query
- Go to timeline page and try reducing the scale
=> Fix issue #58: Scaling

next.config.ts, package.json, tailwind.config.ts
Closes #60 
Now `yarn format` is run on the same dirs as `next lint`; see first lines of `next lint -h` below:
```
Usage: next lint [directory] [options]
Runs ESLint for all files in the `/src`, `/app`, `/pages`, `/components`, and `/lib` directories.
```
- Try chaging files outside these dirs with something that the formatter shouldn't allow (single quotes or spaces)
- Verify that both `yarn lint` (`next lint`) and `yarn format` don't change them back
=> Fix issue #60: Lint at root dir

.github/workflows/CI.yml
Closes #80 
Put the tests at the end at the pipeline so that the lint is still checked
Look at the pipeline that ran on this PR
=> Fix issue #80: Put tests at the end to check lint

components/PlanSelector.tsx
Closes #75 
Hide the PlanSelector when in the submit-query page.
- Go to page `submit-query`
- Submit a query
- The PlanSelector should not appear
- Go to any visualisation page
- The PlanSelector should appear
=> Fix issue #75: don't show PlanSelector when in query page

app/timeline/page.tsx, components/TimeScale.tsx, components/index.ts
Closes #86 
Add a time scale under the timescale.
The ticks are evenly spaced, they are added/removed when zooming/dezooming
- Send a query
- Go to the timeline page and see the time scale
=> Fix issue #86: time scale for timeline

app/submit-query/page.tsx, components/FileUploader.tsx
Closes #90 
The default parameters values for the FileUploader component have been set to ".txt" and "Upload a file"
I precised further information on both components when they are called.
MDX request file must be .txt
Query plan can be .txt or .json
Go to page: submit-query
Check that the information appears on the file uploaders, and that the extension requirements listed above are required.
=> Fixing issue #90 : being more clear about file inputs

app/submit-query/page.tsx
Closes #93 
Add overflow options for the query plan display box
- Send a request
- Reduce the width of your screen. Now if it overflows, the black stays inside the green, and you can slide the text left/right
=> Fix issue #93: query plan overflow

app/submit-query/page.tsx, components/FileExporter.tsx, components/index.ts
Closes #89 
If there is a loaded query plan, it can be exported as a JSON file
Go to page: submit-query
Load a query plan
Check that you can download it as JSON file and that the file is correct
=> Fixing issue #89 : exporting Query plans as JSON files

app/timeline/page.tsx
Closes #87 
The timeline have a minimum size, so that it is always visible 
Add your query plan
Go to the timeline page
Try reducing the size
=> Fixing issue #87: Have a minimum size for timeline

components/CoreTimeline.tsx, components/Providers.tsx, lib/functions/buildTimeline.ts
Closes #104 
Have different colors for different types in timeline, for easier analysis
- Send a query
- Go to timeline page, and see
Should I put a legend on top?
=> Fix issue #104: different colors for different types in timeline

app/timeline/page.tsx, components/timeline/TimelineFooter.tsx
Closes #108 
- [x ] ~use `onWheel` instead of `useEffect`~ we decided it's better to keep it
- Send a query
- Go to the timeline page and see if scroll and wheel behavior still work
=> Fix issue #108: use onScroll and onWheel if possible

app/submit-query/page.tsx
Closes #112 
Add a loading _indication_ (not message) after 800ms
- Try to send a query : as soon as you send, the button should be disabled. If it takes more than 800ms, you should see a rotating circle to indicate loading. If you can't get a long enough request, you can temporarily change the 800ms to 100ms, and you should see it.
=> Fix issue #112: loading indication

app/summary/page.tsx
Closes #113 
Improving summary page information display
Go to page: summary
Check that the changes work
There are a lot of changes to read since I changed the structure which moved blocks of code
I advise directly reading the page itself
=> Issue #113: reorganising summary page display

components/RetrievalDialog.tsx
Closes #128 
In the custom card that displays info about the retrieval when clicked on, on pages timeline and slowest nodes
In the TimingInfo section:
Launch app
Go to page timeline or slowest nodes
Click on a retrieval
Check that the features listed in description work
=> Fix retrieval custom visual

lib/functions/slowestNodes.ts
Closes #136 
Nodes pages crash when a retrieval gives `"timingInfo": {}`
This is something that can still happen, as I got it from a generated query plan, so it is not related to the old version and **must be fixed**
Related to #133 
The error is that the key `startTime` does not exist so `const startTimes: number[] = timingInfo.startTime;` creates something undefined
Fixed by avoiding to use timingInfo without keys in the function, and by returning all zeros if the function takes an `{}` timingInfo
Test with a queryPlan containing a `"timingInfo": {}` (examples in #135 ) and check that all the pages, including `Nodes`, work
@TimotheeVrg I modified your page
=> Fixing nodes crash empty timing info

app/timeline/page.tsx, components/RetrievalDialog.tsx, components/timeline/CoreProcesses.tsx, components/timeline/TimelineLegend.tsx, lib/functions/buildTimeline.test.ts, lib/functions/buildTimeline.ts, lib/types/timeline.ts
Closes #129 
- Add a time mode displaying process in a green-to-red scale according to their duration
- Add a threshold to "keep" only longer processes and an indicator on the above-mentioned green-to-red scale
- Send a query
- Go to timeline page, test the threshold, test the time mode, test both at the same time
=> Fix issue #129: Timeline time modes

components/RetrievalDialog.tsx
Closes #142 
Value no longer overflow to the side if too many of them
Click on a node on `Nodes` or `Timeline` page from a very large query plan and check that there is a side bar and the display is correct
I suggest `all-countries - contributors query - slow.json` from issue #135
=> fix : retrieval card overflow

app/nodes/page.tsx, lib/functions/slowestNodes.test.ts, lib/functions/slowestNodes.ts, lib/types/index.ts
Closes #127 
Add a new column in the SlowestNodes table : Max Timing 
Rename the previous "Timing" column by Total Timing
Add tooltips in the head of the table so that it easier to understand
Add your query plan
Go to the "Nodes" page
Look at the new column, and the tooltips
=> Fix issue #127: Different columns for timings in the slowest nodes table

app/summary/page.tsx
Closes #153 
A card in sumamry page has a fixed color; we remove it
In all cases this card will probably be removed completely if aggregate is placed in the header
Summary page: check that the card for aggregation is readable in light mode
=> fix : removing fixed color

app/nodes/page.tsx, app/summary/page.tsx, app/timeline/page.tsx, components/PlanSelector.tsx, components/timeline/CoreProcesses.tsx, lib/functions/aggregation/aggregateData.test.ts, lib/functions/aggregation/aggregateData.ts, lib/functions/buildTimeline.test.ts, lib/functions/buildTimeline.ts, lib/functions/slowestNodes.test.ts, lib/functions/slowestNodes.ts, lib/types/index.ts, lib/types/queryPlan.ts, lib/types/timeline.ts
Closes #140 
Add an option in the list to aggregate all data directly in the header
- Send a query
- Go to the visualization pages and test the aggregation
=> Fix issue #140: aggregate data in header

app/passes/layout.tsx, app/passes/page.tsx, components/Header.tsx, components/PlanSelector.tsx, lib/functions/index.ts, lib/functions/passesTimings.test.ts, lib/functions/passesTimings.ts, lib/types/queryPlan.ts
Closes #126 
Add a new page to determine the longest passes
Please note: very simple page for the moment, only a basic table, destined to evolve in the future
The PlanSelector is desactivated in the header in this page
Unit tests are performed for the function used
Load a query plan (with several passes)
Go to page: "Passes"
=> Fixing issue #126: add a new page to determine the longest passes

components/RetrievalDialog.tsx
Closes #151 
Numbers of `timingInfo` are now only aligned, no more option, as requested
Launch the app
Load a query plan with some timings
Check on `nodes` or `timeline` page by clicking on a node that the display of `timingInfo` numbers is aligned.
`use client;` was added to that component to use useState but was not there from the beginning, so I deleted it again
=> fix : align only mode for card display

app/nodes/page.tsx, app/passes/page.tsx, components/index.ts, components/nodes/NodesLegend.tsx, components/nodes/NodesTable.tsx, components/nodes/index.ts, components/timeline/CoreProcesses.tsx, components/timeline/TimelineLegend.tsx, lib/functions/slowestNodes.test.ts, lib/functions/slowestNodes.ts, lib/types/index.ts, lib/types/timeline.ts
Closes #152 
Add components in the slowest nodes page
Add a colored legend and colors in the table
Add a query plan
Go to the “Nodes” page
See the colors in the table (try changing the sorting in the different columns)
=> Fixing issue #152: add colors in the slowest nodes page

app/submit-query/page.tsx
Closes #168 
User can now give a query plan on V1 format entering a file or directly text
Go to page: submit-query
Get a V1 query plan. I suggest copying the one in the `convertV1ToJson.test.ts` an placing it in a file
Test that it is accepted and is correctly analysed by our tool like any query plan
=> Fix issue #168: V1 format now accepted

app/nodes/page.tsx, lib/functions/slowestNodes.ts
Closes #164 
Before in the Nodes Page, when sorting by another column, it only sorted the displayed retrievals and not all the retrievals.
Currently, the sort function is checking all the nodes
Load your query plan
Go to page "Nodes"
Try to change the different column sort
=> Fixing issue #164: problems when sorting the slowest nodes

app/summary/page.tsx
Closes #186 
Tooltips of last sections of summary page, where there is information about partial providers and partitioning, reworked (three of them now)
Load a query plan
Go to page: summary-page
Check that the display of tooltips at the end of the page is good
=> Fix issue #186 : Rework summary page tooltips

app/timeline/page.tsx, components/timeline/CoreProcesses.tsx
Closes #163 
- Fix width of small nodes div (when no unit is provided, it's auto `px` but if below 1 convert to percent)
- Better scale: min is now full timeline, max is 25 (enough to see 1ms nodes)
- Send a big query with lots of small nodes
- See that the timeline is now correctly displayed
- Test the new scale method
=> Fix issue #163: Timeline display

app/nodes/page.tsx, components/nodes/NodesTable.tsx
Contribute to #160 
Better performance in the Nodes Page
- Precompute some values when changing sortColumn or sortOrder
- Add a loading circle
- getRetrievalFromNode (O(n) -> O(1))
Go to page: Nodes (with a query plan with lots of retrievals)
See if that still works
=> Contribute to issue #160: Better performance in Nodes Page

app/api/process-query-plan/route.ts, app/api/timeline/route.ts, app/submit-query/ui/ManualMode.tsx, app/timeline/page.tsx, lib/functions/buildTimeline.test.ts, lib/functions/buildTimeline.ts, lib/types/timeline.ts
Closes #184 
Closes #181 
- Compute timeline on server
- Parse Query Plan on server
- Add loading animations while these
- Launch the heavy Query Plan of #160 
- Your computer should not be overloaded
For consistency I would like to do it for the nodes and summary pages, but they don't have a heavy load. I think it is useless to have such a heavy logic for these pages.
=> Fix issue #184: Compute on server

app/nodes/page.tsx, app/timeline/page.tsx, components/nodes/NodesTable.tsx
Closes #196 
Contributes to #160 
- Fix retrieval when aggregated bug
- Also use O(1) function in timeline
- Send a query plan with several Select Pass
- Go to nodes page and test that now, when aggregated, you get the correct retrieval
- Go to timeline and checks that it still works
=> Contribute to #160 and fix #196

app/summary/page.tsx, app/summary/ui/SummarySection.tsx, app/summary/ui/TimingList.tsx, app/summary/ui/TimingPieChart.tsx, lib/types/index.ts
Closes #198
Contributes to #199 
Refactoring summary page, adding components and avoiding repeats
Load a query plan
Go to page: `summary`
Check that the page behaves exactly like main
=> Fixing issue #198 : refactoring summary page

app/summary/page.tsx, app/summary/ui/TimingList.tsx
"ms" was displaying for the number of retrievals, that has no unit.
Load a query plan
Go to page: summary
Check that the display is correct
=> Fixing bug : "ms" unit displaying when not needed
